### ISSUE TITLE
[Pre-trained Model]

### ISSUE THREAD

**Issue by Papirapi** [gaussianrecurrence/semantic-segmentation-multi-keras#1]
Hi, thanks for sharing your code.
But seems like the model-weights.h5 file is corrupted.
Could you please provide me with more details about the used Model: (architecture (Vgg, Resnet ......???))
Thanks

**Comment by msdt93** [comment]
First of I need to know the following things in order to find out what's happening:
 - Which Python version are you using?
 - Which Tensorflow are you using?
 - Which Keras version are you using?
 - Under which hardware are you trying to load the model? (CPU/GPU/TPU)

**Comment by msdt93** [comment]
Regarding the network topology it's not any of the one existing... but it's quite similar to ResNet
If you read the below linked article describing the model you will found out a little bit more about the network.

“Topology” — https://link.medium.com/L4DguvYER0

**Comment by Papirapi** [comment]
Python 3.6
Tensorflow 1.14+
Keras 2+
Gpu
My supervisor got me an account on Valohai platform

**Comment by Papirapi** [comment]
Python 3.6
Tensorflow 1.14+
Keras 2+
Gpu
Many thanks for the quick response

**Comment by msdt93** [comment]
I think the problem is that I used an older version of Keras to generate weights, so maybe they changed the format. I uploaded a Google Colab notebook in here: https://colab.research.google.com/drive/1I6A7ChKDmApP2rA3f2yNsFn4wASgQZOL and executing it again to obtain updated weights.

**Comment by msdt93** [comment]
I've tried to load weights in the same environment you mentioned and this is working fine to me. Maybe the way you are downloading the file is making it corrupt.

I modified the Google Colab notebook in order to be able to download and load the weights with fixed versions of dependencies.

Let me know If there's anything else I can look into :)

**Comment by Papirapi** [comment]
Works fine! Many thanks for your  time and effort :)
